version: "3"
services:

  # client 
  client:                 
    build:
      dockerfile: Dockerfile.dev
      context: ./client    
    volumes:
      - ./client/:/app      
      - /app/node_modules  
    networks:
      - backend    

  # server        
  server:                          
    build:
      dockerfile: Dockerfile.dev
      context: ./server    
    volumes:
      - ./server/:/app      
      - /app/node_modules      
    environment:
      - NODE_PATH=src
      - PORT=3050
      - DB_HOST=mongo
      - DB=test
      - REDIS_HOST=redis
      - REDIS_PORT=6379      
    networks:
      - backend  
    depends_on:
      - pf_mongo
      - pf_redis 
    ports: # 호스트:컨테이너 / 문자열로 지정해야 함 
      - "5000:3050"   

  # redis 
  pf_redis:
    container_name: pf_redis
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - backend 
    volumes: # 호스트 쪽의 경로를 지정, 호스트:컨테이너
      - data:/data/redis   
    ports:
      - "6379:6379"
    restart: always    

  # mongo
  pf_mongo:
    container_name: pf_mongo
    image: mongo
    volumes:
      - data:/data/db
    ports:
      - "27017:27017" 
    networks:
      - backend

  # nginx
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx 
    ports:
      - '3000:80' 
    networks:
      - backend
    

networks: 
  backend:
    driver: bridge

volumes:
  data:
    driver: local 